In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [4]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
#X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [7]:
X_train

array([[8, 'Female', 101.0, 'Mild', 'Kolkata'],
       [16, 'Male', 104.0, 'Mild', 'Kolkata'],
       [64, 'Female', 98.0, 'Mild', 'Bangalore'],
       [48, 'Female', 103.0, 'Mild', 'Kolkata'],
       [10, 'Male', 100.0, 'Mild', 'Bangalore'],
       [20, 'Male', 102.0, 'Strong', 'Delhi'],
       [16, 'Female', 103.0, 'Mild', 'Bangalore'],
       [12, 'Male', 98.0, 'Strong', 'Bangalore'],
       [27, 'Male', 100.0, 'Mild', 'Delhi'],
       [33, 'Female', 102.0, 'Strong', 'Delhi'],
       [60, 'Male', 103.0, 'Mild', 'Kolkata'],
       [54, 'Female', 104.0, 'Strong', 'Kolkata'],
       [15, 'Male', 101.0, 'Mild', 'Delhi'],
       [47, 'Female', 100.0, 'Strong', 'Bangalore'],
       [44, 'Male', 104.0, 'Mild', 'Mumbai'],
       [47, 'Male', 101.0, 'Strong', 'Bangalore'],
       [83, 'Female', 101.0, 'Mild', 'Kolkata'],
       [69, 'Female', 103.0, 'Mild', 'Kolkata'],
       [70, 'Male', 103.0, 'Strong', 'Kolkata'],
       [34, 'Female', 104.0, 'Strong', 'Delhi'],
       [23, 'Male', 98.0, 

## 1. Impute fever column


In [8]:
# adding simple imputer to fever col
si = SimpleImputer()
#X_train_fever = si.fit_transform(X_train[:,1])
X_train_fever = si.fit_transform(X_train[:,2].reshape(-1,1))

# also the test data
#X_test_fever = si.fit_transform(X_test[['fever']])
X_test_fever = si.fit_transform(X_test[:,2].reshape(-1,1))                                 
#X_train_fever.shape

In [9]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[:,3].reshape(-1,1))

# also the test data
X_test_cough = oe.fit_transform(X_test[:,3].reshape(-1,1))

X_train_cough.shape

(80, 1)

In [10]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse=False)
X_train_gender = ohe.fit_transform(X_train[:,1].reshape(-1,1))
X_train_city = ohe.fit_transform(X_train[:,4].reshape(-1,1))
# also the test data
X_test_gender = ohe.fit_transform(X_test[:,1].reshape(-1,1))
X_test_city = ohe.fit_transform(X_test[:,4].reshape(-1,1))


X_train_city


C:\Users\anilk\anaconda311\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\anilk\anaconda311\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\anilk\anaconda311\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\anilk\anaconda311\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed 

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0

In [11]:
# Extracting Age
X_train_age = X_train[:,0].reshape(-1,1)
# also the test data
X_test_age = X_test[:,0].reshape(-1,1)

X_train_age.shape

(80, 1)

In [12]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender,X_train_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender,X_test_city,X_test_cough),axis=1)

X_train_transformed

array([[8, 101.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [16, 104.0, 1.0, 0.0, 1.0, 0.0, 0.0],
       [64, 98.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [48, 103.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [10, 100.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [20, 102.0, 1.0, 1.0, 0.0, 0.0, 1.0],
       [16, 103.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [12, 98.0, 1.0, 0.0, 0.0, 0.0, 1.0],
       [27, 100.0, 1.0, 1.0, 0.0, 0.0, 0.0],
       [33, 102.0, 0.0, 1.0, 0.0, 0.0, 1.0],
       [60, 103.0, 1.0, 0.0, 1.0, 0.0, 0.0],
       [54, 104.0, 0.0, 0.0, 1.0, 0.0, 1.0],
       [15, 101.0, 1.0, 1.0, 0.0, 0.0, 0.0],
       [47, 100.0, 0.0, 0.0, 0.0, 0.0, 1.0],
       [44, 104.0, 1.0, 0.0, 0.0, 1.0, 0.0],
       [47, 101.0, 1.0, 0.0, 0.0, 0.0, 1.0],
       [83, 101.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [69, 103.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [70, 103.0, 1.0, 0.0, 1.0, 0.0, 1.0],
       [34, 104.0, 0.0, 1.0, 0.0, 0.0, 1.0],
       [23, 98.0, 1.0, 0.0, 0.0, 1.0, 1.0],
       [72, 99.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [64, 101

## using ColumnTransformer


In [13]:
from sklearn.compose import ColumnTransformer

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2,random_state = 1)
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [15]:
X_train=transformer.fit_transform(X_train)
X_train

C:\Users\anilk\anaconda311\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  42.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  20.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [100.95833333,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  42.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  82.        ],
       [100.95833333,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  79.        ],
       [102.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  33.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.    

In [16]:
transformer.transform(X_test).shape

(20, 7)